language: node_js
node_js:
  - lts/*
env:
  global:
    - SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=zaQVFPoDNH8C69eCILMzPzi9qhZEm1Dws
install:
  - rm -rf node_modules
  - yarn install
script:
  - yarn build
  - yarn coverage